stages:
  - get
  - vault
  - build-full
  - build-core

image: alpine

before_script:
  - apk add --no-cache git wget curl jq
  - git config --global http.sslVerify false

get_packer:
  stage: get
  tags:
    - bash
  artifacts:
    paths:
    - packer
  script:
    - echo "Fetching packer"
    - wget $packerURL/$packerVersion/packer_"$packerVersion"_linux_amd64.zip
    - unzip packer_"$packerVersion"_linux_amd64.zip
    - chmod +x packer

retrieve_vault_password:
  stage: vault
  tags:
    - bash
  artifacts:
    paths:
    - windows-2019/setup/Autounattend.xml
    - windows-2022/setup/Autounattend.xml
  script:
    - xmlFiles='windows-2019/setup/Autounattend.xml windows-2022/setup/Autounattend.xml'
    - echo "Retrieving Administrator password from Vault"
    - adminPW=$(curl -k -s -H "X-Vault-Token:$VAULT_TOKEN" -X GET $VAULT_ADDR/v1/credentials/users/misc/administrator | jq '.data.Password' | sed 's/^.//;s/.$//')
    - echo "Updating Autounattend.xml file with Administrator password"
    - for i in ${xmlFiles}; do sed -i "s/{{password}}/$adminPW/g" $i; done

build_centos-8:
  stage: build-full
  tags:
    - bash
  script:
    - echo "Deploying CentOS 8"
    - cd centos-8
    - ../packer init .
    - ../packer build -force .

build_windows-2019:
  stage: build-full
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2019"
    - cd windows-2019
    - ../packer init .
    - ../packer build -force .

build_windows-2022:
  stage: build-full
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2022"
    - cd windows-2022
    - ../packer init .
    - ../packer build -force .

build_windows-2019-core:
  stage: build-core
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2019 Server Core"
    - cd windows-2019
    - sed -i "s/Windows Server 2019 Standard/Windows Server 2019 Core/g" windows-2019.pkr.hcl
    - sed -i "s/SERVERSTANDARD/SERVERSTANDARDCORE/g" setup/Autounattend.xml
    - ../packer init .
    - ../packer build -force .

build_windows-2022-core:
  stage: build-core
  tags:
    - bash
  script:
    - echo "Deploying Windows Server 2022 Server Core"
    - cd windows-2022
    - sed -i "s/Windows Server 2022 Standard/Windows Server 2022 Core/g" windows-2022.pkr.hcl
    - sed -i "s/SERVERSTANDARD/SERVERSTANDARDCORE/g" setup/Autounattend.xml
    - ../packer init .
    - ../packer build -force .